# Generated by Django 5.1.6 on 2025-03-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="profile_pic",
            new_name="profile_picture",
        ),
    ]
