# Generated by Django 5.1.6 on 2025-03-26 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_profile_pic_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="following_users", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="follower_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
